---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: rook-ceph-block-slow
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: pihole
  name: pihole
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pihole
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        v1.multus-cni.io/default-network: '[{"mac":"ca:b8:b9:2a:b3:42","name":"general-vlan-static","namespace":"kube-system","ips":["10.47.10.5/24"],"default-route":["10.47.10.1"]}]'
      labels:
        app: pihole
    spec:
      containers:
      - image: pihole/pihole:v5.2.1@sha256:5281797ed544ae438cd3c458171212d1e0cbf5c219a1cffe28b042a9f9821791
        name: pihole
        ports:
          - containerPort: 53
            name: dns
            protocol: UDP
          - containerPort: 53
            name: dns-tcp
            protocol: TCP
          - containerPort: 80
            name: http
            protocol: TCP
          - containerPort: 443
            name: https
            protocol: TCP
        env:
          - name: TZ
            value: "America/New_York"
        resources:
          limits:
            memory: 768Mi
          requests:
            cpu: 100m
            memory: 256Mi
# TODO: Adjust these - readonlyfs needs emptydir in certain locations
#        securityContext:
#          allowPrivilegeEscalation: false
#          capabilities:
#            add:
#              - NET_BIND_SERVICE
#            drop:
#              - all
#          readOnlyRootFilesystem: true
        volumeMounts:
          - mountPath: "/etc/pihole"
            name: pihole-storage
      # This is designed to bypass any bootstrap circular dependencies for DNS
      dnsPolicy: "None"
      dnsConfig:
        nameservers:
          - "1.1.1.1"
          - "8.8.8.8"
      volumes:
        - name: pihole-storage
          persistentVolumeClaim:
            claimName: pihole-pvc
