apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: debian-buster-iso
spec:
  source:
      http:
         url: "https://cdimage.debian.org/debian-cd/current/amd64/iso-cd/debian-10.6.0-amd64-netinst.iso"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "400Mi"
    storageClassName: rook-ceph-block-slow
