---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ece-disk
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: local-storage

---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ece
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: ece
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
#          - bootOrder: 1
#            cdrom:
#              bus: sata
#            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          interfaces:
            - name: eth0
              bridge: { }
              macAddress: 02:00:00:8a:32:4e
        resources:
          requests:
            memory: 16Gi
      networks:
        - name: eth0
          multus:
            networkName: general-vlan
      volumes:
#      - name: cdromiso
#        dataVolume:
#          name: ubuntu-bionic-iso
      - name: harddrive
        persistentVolumeClaim:
          claimName: ece-disk
