apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu-bionic-iso
spec:
  source:
      http:
         url: "http://archive.ubuntu.com/ubuntu/dists/bionic/main/installer-amd64/current/images/netboot/mini.iso"
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: "400Mi"
    storageClassName: rook-ceph-block-slow
